baseURL = 'https://orbiopleidingen.pages.dev/'
DefaultContentLanguage = 'nl'
title = 'Orbi Opleidingen'
theme = "bootstrap"

[languages]
  [languages.nl]
    title = 'Orbi Opleidingen'
    weight = 1
    LanguageName = 'Nederlands'

  [languages.en]
    title = 'Orbi Education'
    weight = 2
    LanguageName = 'English'
    [languages.en.params]
      linkedin = 'https://linkedin.com/whoever'